idf_component_register(
    SRC_DIRS
        "system"
        "devices"
        "drivers"
        "drivers/bus"
    EXCLUDE_SRCS
        "devices/mpu6050_dev.cpp"
        "drivers/mpu6050.cpp"
        "drivers/bus/uart_bus.cpp"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp_driver_gpio
        esp_driver_i2c
        esp_timer
)
